function run_subject_2(myPaths, id)
% RUN_SUBJECT_2 EEG postprocessing, epoching, spectral metrics, and QA (Part 2).
%
% Syntax:
%   run_subject_2(myPaths, id)
%
% Description:
%   Executes the second stage of the automated EEG preprocessing pipeline using
%   the cleaned continuous output generated by Part 1.
%
%   Key processing steps:
%     1. Continuous low-pass FIR filtering.
%     2. Individual Alpha Frequency (IAF) estimation (resting-state blocks).
%     3. Task- and event-locked segmentation and epoching.
%     4. Common-average re-referencing and baseline correction.
%     5. Multi-tier bad epoch detection and outlier removal.
%     6. Residual artefact screening (ocular leftovers and high-frequency EMG slopes).
%     7. Sensor covariance and channel correlation matrix estimation.
%     8. Standardised Automagic quality metric scoring (RBC, OHA, THV, CHV).
%     9. Generation and export of summary QA figures and diagnostic reports.
%    10. BIDS-compliant metadata structuring and final data export.
%
% Inputs:
%   myPaths - Structure containing directory and session configurations:
%               .mycodes     : Path to pipeline source code
%               .rootrawdata : Directory containing raw BDF files
%               .rootpreproc : Output root directory for preprocessed data
%               .task        : Task identifier (e.g., 'RS', 'EO', 'EC', 'MT')
%               .group       : Study cohort or group identifier (e.g., 'AFM', 'ALS')
%               .codever     : Pipeline code version string (e.g., '2')
%               .proctime    : Launch timestamp string used for procTimeTags
%   id      - String or character array specifying participant ID (e.g., 'SUBJ001')
%
% Outputs:
%   None (final epoched datasets, BIDS structures, and QA plots are saved to disk).
%
% ALS Centre, University Medical Centre Utrecht
% License: GNU General Public License v3.0

% Load preprocessing settings
cfg = preproc_parameters;

% -------------------------------------------------------------------------
% Define paths and files
% -------------------------------------------------------------------------
subject = preproc_folders_subject(id, myPaths, 2);

% Print
fprintf('\n==================================================================\n');
fprintf('%s | %s | %s dataset | processing part 2 | pipeline v%s\n', myPaths.group, subject.id, myPaths.task, myPaths.codever);
fprintf('==================================================================\n');

% Load cleaned data
fileName = fullfile(subject.data, subject.clnfile0);
if exist(fileName, 'file') == 2
    fprintf('\n================================\n');
    fprintf('Loading data\n');
    fprintf('================================\n');

    load(fileName, 'EEG');
    fprintf('Done!\n');
else
    warning([subject.id ' is missing preprocessed ' myPaths.task ' data. Skipping...']); return;
end

% Time
t0 = datetime("now");
EEG.ALSUTRECHT.procTimeTags = {myPaths.proctime; strrep(strrep(char(t0),':','-'),' ','-')};

% -------------------------------------------------------------------------
% Basic post-preprocessing
% -------------------------------------------------------------------------

% Filter lowpass (should be done on continuous data)
EEG = do_filtering(EEG, 'lowpass', cfg.flt);

% % Empirical frequency boundaries (only RS)
% EEG = estimate_gedBounds(EEG);

% IAF (only RS?)
EEG = check_iaf(EEG);

% Epoch
EEGcell = epoch_data(EEG, cfg.trg);
clearvars EEG

% -------------------------------------------------------------------------
% Loop through epoched datasets
% -------------------------------------------------------------------------
for i_file = 1:length(EEGcell)
    % Extract
    EEG = EEGcell{i_file};

    % Common-average referening
    EEG = do_reref(EEG, 'aRegular');

    % Baseline correction
    EEG = do_baselinecorrection(EEG, 'traditional');

    % Detect bad epochs
    [EEG, num_trials] = detect_badepochs(EEG, cfg);

    % Final estimates
    fprintf('\n================================\n');
    fprintf('Final data estimates\n');
    fprintf('================================\n');

    % EOG leftovers
    fprintf('\nChecking EOG leftovers..\n');
    EEG = check_blink_residuals(EEG);
    num_trials(end + 1) = EEG.trials;

    % EMG leftovers
    fprintf('\nChecking EMG leftovers...\n');
    [slopes, mask_emg_matrix] = detect_emg(EEG, cfg);
    emg_leftover = mean(mask_emg_matrix, 'all');
    fprintf('EMG leftovers: %1.2f\n', emg_leftover);

    % Median voltage shift
    fprintf('\nEstimating voltage range...\n\n');
    voltage_shift = median(range(EEG.data, 2), 3);

    % Channel correlation matrix
    fprintf('Estimating channel correlation matrix..\n');
    EEG = estimate_channelcov(EEG);

    % Automagic metrics
    bad_chans = length(EEG.ALSUTRECHT.badchaninfo.badElectrodes);
    quality = report_automagic(EEG, bad_chans, 'ThresholdOHA', 30, 'ThresholdStd', 15);

    fprintf('\nAutomagic quality metrics:\n');
    fprintf('RBC (Bad Channels):   %.2f%%\n', quality.RBC * 100);
    fprintf('OHA (High Amp):       %.2f%%\n', quality.OHA * 100);
    fprintf('THV (Bad Times):      %.2f%%\n', quality.THV * 100);
    fprintf('CHV (Noisy Channels): %.2f%%\n', quality.CHV * 100);
    fprintf('Status:               %s\n',     quality.status);

    % Log
    EEG.ALSUTRECHT.epochRejections.MedianvoltageshiftwithinepochFinal = voltage_shift;
    EEG.ALSUTRECHT.epochRejections.muscle2 = emg_leftover;
    EEG.ALSUTRECHT.leftovers.muscle2       = emg_leftover;
    EEG.ALSUTRECHT.automagicmetrics        = quality;

    % Final reports/plots
    generate_finalplots(EEG, num_trials, myPaths.task, i_file, cfg);

    % EEGLAB / BIDS metadata
    EEG = add_bidsmetadata(EEG, subject);

    % Save data
    export_data(EEG, subject, i_file);
end

% Report
t1 = datetime("now");
dd = round(minutes(diff([t0 t1])));
fprintf('Finished: %s\n', t1);
fprintf('Running time: %d min.\n\n', dd);

end